### ISSUE TITLE
java.lang.RuntimeException: /tmp/sync/tables is not initialed

### ISSUE THREAD

**Issue by liangrui1988** [allwefantasy/delta-plus#14]
java.lang.RuntimeException: /tmp/sync/tables is not initialed
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$$anonfun$saveToSink$1$1.apply(BinlogSyncToDelta.scala:107)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$$anonfun$saveToSink$1$1.apply(BinlogSyncToDelta.scala:82)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$.saveToSink$1(BinlogSyncToDelta.scala:82)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$.run(BinlogSyncToDelta.scala:132)
	at org.apache.spark.sql.delta.sources.MLSQLDeltaSink.addBatch(MLSQLDeltaSink.scala:31)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$17.apply(MicroBatchExecution.scala:537)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:535)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:534)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:198)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:160)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:281)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
19/12/09 18:32:43 INFO DAGScheduler: Asked to cancel job group 7eeb5e14-fdb0-42f2-95ff-3c3801060956
19/12/09 18:32:43 ERROR SocketServerInExecutor: The server ServerSocket[addr=windows10.microdone.cn/192.168.232.1,localport=52992] is closing the socket Socket[addr=/192.168.232.1,port=52996,localport=52992] connection
java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.spark.sql.mlsql.sources.mysql.binlog.BinLogSocketServerSerDer$class.readRequest(servers.scala:141)
	at org.apache.spark.sql.mlsql.sources.mysql.binlog.BinLogSocketServerInExecutor.readRequest(BinLogSocketServerInExecutor.scala:29)
	at org.apache.spark.sql.mlsql.sources.mysql.binlog.BinLogSocketServerInExecutor.handleConnection(BinLogSocketServerInExecutor.scala:412)
	at org.apache.spark.sql.mlsql.sources.mysql.binlog.SocketServerInExecutor$$anonfun$2.apply(servers.scala:128)
	at org.apache.spark.sql.mlsql.sources.mysql.binlog.SocketServerInExecutor$$anonfun$2.apply(servers.scala:127)
	at org.apache.spark.sql.mlsql.sources.mysql.binlog.SocketServerInExecutor$$anon$3$$anon$4.run(servers.scala:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
19/12/09 18:32:43 INFO TaskSchedulerImpl: Cancelling stage 3
19/12/09 18:32:43 INFO TaskSchedulerImpl: Killing all running tasks in stage 3: Stage cancelled
19/12/09 18:32:43 INFO Executor: Executor is trying to kill task 0.0 in stage 3.0 (TID 51), reason: Stage cancelled
19/12/09 18:32:43 INFO SocketServerInExecutor: Received connection fromSocket[addr=/192.168.232.1,port=53003,localport=52992]
19/12/09 18:32:43 INFO TaskSchedulerImpl: Stage 3 was cancelled
19/12/09 18:32:43 INFO BinLogSocketServerInExecutor: Shutdown ServerSocket[addr=windows10.microdone.cn/192.168.232.1,localport=52992]. This may caused by the task is killed.
19/12/09 18:32:43 ERROR SocketServerInExecutor: The server ServerSocket[addr=windows10.microdone.cn/192.168.232.1,localport=52992] is closing the socket Socket[addr=/192.168.232.1,port=53003,localport=52992] connection
java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.spark.sql.mlsql.sources.mysql.binlog.BinLogSocketServerSerDer$class.readRequest(servers.scala:141)
	at org.apache.spark.sql.mlsql.sources.mysql.binlog.BinLogSocketServerInExecutor.readRequest(BinLogSocketServerInExecutor.scala:29)
	at org.apache.spark.sql.mlsql.sources.mysql.binlog.BinLogSocketServerInExecutor.handleConnection(BinLogSocketServerInExecutor.scala:412)
	at org.apache.spark.sql.mlsql.sources.mysql.binlog.SocketServerInExecutor$$anonfun$2.apply(servers.scala:128)
	at org.apache.spark.sql.mlsql.sources.mysql.binlog.SocketServerInExecutor$$anonfun$2.apply(servers.scala:127)
	at org.apache.spark.sql.mlsql.sources.mysql.binlog.SocketServerInExecutor$$anon$3$$anon$4.run(servers.scala:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
19/12/09 18:32:43 INFO DAGScheduler: ResultStage 3 (start at MlsqlTest.scala:38) failed in 8.136 s due to Job 1 cancelled part of cancelled job group 7eeb5e14-fdb0-42f2-95ff-3c3801060956
19/12/09 18:32:43 INFO DAGScheduler: Job 1 failed: start at MlsqlTest.scala:38, took 8.146706 s
Exception in thread "main" org.apache.spark.sql.streaming.StreamingQueryException: /tmp/sync/tables is not initialed
=== Streaming Query ===
Identifier: [id = e81608b0-b6b0-489c-ba18-adeef486cb4d, runId = 874f489f-4011-41e4-92d3-23bc0194813f]
Current Committed Offsets: {MLSQLBinLogSource(ExecutorBinlogServer(windows10.microdone.cn,52992),org.apache.spark.sql.SparkSession@1ec5199e,file:///tmp/cpl-binlog2/sources/0,Some(10000000008171),Map(binglognameprefix -> mysql-bin, tablenamepattern -> script_file, databasenamepattern -> mbcj_test, binlogindex -> 1, username -> root, host -> 10.200.102.197, port -> 3306, binlogserverid -> 7eeb5e14-fdb0-42f2-95ff-3c3801060956, binlogfileoffset -> 8171, password -> candao)): 10000000008376}
Current Available Offsets: {MLSQLBinLogSource(ExecutorBinlogServer(windows10.microdone.cn,52992),org.apache.spark.sql.SparkSession@1ec5199e,file:///tmp/cpl-binlog2/sources/0,Some(10000000008171),Map(binglognameprefix -> mysql-bin, tablenamepattern -> script_file, databasenamepattern -> mbcj_test, binlogindex -> 1, username -> root, host -> 10.200.102.197, port -> 3306, binlogserverid -> 7eeb5e14-fdb0-42f2-95ff-3c3801060956, binlogfileoffset -> 8171, password -> candao)): 10000000009869}

Current State: ACTIVE
Thread State: RUNNABLE

Logical Plan:
MLSQLBinLogSource(ExecutorBinlogServer(windows10.microdone.cn,52992),org.apache.spark.sql.SparkSession@1ec5199e,file:///tmp/cpl-binlog2/sources/0,Some(10000000008171),Map(binglognameprefix -> mysql-bin, tablenamepattern -> script_file, databasenamepattern -> mbcj_test, binlogindex -> 1, username -> root, host -> 10.200.102.197, port -> 3306, binlogserverid -> 7eeb5e14-fdb0-42f2-95ff-3c3801060956, binlogfileoffset -> 8171, password -> candao))
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:297)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
Caused by: java.lang.RuntimeException: /tmp/sync/tables is not initialed
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$$anonfun$saveToSink$1$1.apply(BinlogSyncToDelta.scala:107)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$$anonfun$saveToSink$1$1.apply(BinlogSyncToDelta.scala:82)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$.saveToSink$1(BinlogSyncToDelta.scala:82)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$.run(BinlogSyncToDelta.scala:132)
	at org.apache.spark.sql.delta.sources.MLSQLDeltaSink.addBatch(MLSQLDeltaSink.scala:31)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$17.apply(MicroBatchExecution.scala:537)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:535)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:534)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:198)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:160)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:281)
	... 1 more

show master status; 
mysql-bin.000001	8171

insert into......

show master status; 
mysql-bin.000001	9869	

 val df = spark.readStream.
      format("org.apache.spark.sql.mlsql.sources.MLSQLBinLogDataSource").
      option("host","10.200.102.197").
      option("port","3306").
      option("userName","root").
      option("password","candao").
      option("bingLogNamePrefix","mysql-bin").
      option("databaseNamePattern","mlsql_console").
      option("tableNamePattern","script_file").
      option("binlogIndex","1").
      option("binlogFileOffset","8171").
      load()

//import org.apache.spark.sql.delta.sources.MLSQLDeltaDataSource
    val query= df.writeStream.
      outputMode(OutputMode.Append).
      format("org.apache.spark.sql.delta.sources.MLSQLDeltaDataSource").
      option("__path__","/tmp/sync/tables").
      option("mode","Append").
      option("idCols","id").
      option("duration","5").
      option("syncType","binlog").
      option("checkpointLocation","/tmp/cpl-binlog2").
      option("path","ods_xueli/binlogtest").start()

    query.awaitTermination()

**Comment by allwefantasy** [comment]
Before you run the streaming application, make sure you have fully sync the table , here are the MLSQL code example, you can translate it to DataFrame API:

```sql
connect jdbc where
 url="jdbc:mysql://127.0.0.1:3306/mlsql_console?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false"
 and driver="com.mysql.jdbc.Driver"
 and user="xxxxx"
 and password="xxxx"
 as db_cool;
 
load jdbc.`db_cool.script_file`  as script_file;

run script_file as TableRepartition.`` where partitionNum="2" and partitionType="range" and partitionCols="id"
as rep_script_file;

save overwrite rep_script_file as delta.`mysql_mlsql_console.script_file` ;

load delta.`mysql_mlsql_console.script_file`  as output;
```

**Comment by liangrui1988** [comment]
Really do not understand MLSQL , do not know how to convert.Could you give me a fully synchronized DataFrame API:example, thank you very much

**Comment by allwefantasy** [comment]
> Really do not understand MLSQL , do not know how to convert.Could you give me a fully synchronized DataFrame API:example, thank you very much

Check this  ISSUE: https://github.com/allwefantasy/spark-binlog/issues/11  
There is a example for dataframe api.

**Comment by liangrui1988** [comment]
哦，我没转过来。这个我会，多谢大神。
再请教一个问题：同步全部库里的表，用*号可以吗？
delta同步hive成表结构方式 ,这里有有例子吗？

**Comment by allwefantasy** [comment]
> 哦，我没转过来。这个我会，多谢大神。
> 再请教一个问题：同步全部库里的表，用*号可以吗？
> delta同步hive成表结构方式 ,这里有有例子吗？

可以使用*进行全部同步。因为是支持正则的。 delta 同步成hive表就是普通的两个数据源读取和写入。
