### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.spark.sql.delta.schema.ImplicitMetadataOperation$class.updateMetadata(Lorg/apache/spark/sql/delta/schema/ImplicitMetadataOperation;Lorg/apache/spark/sql/delta/OptimisticTransaction;Lorg/apache/spark/sql/Dataset;Lscala/collection/Seq;Lscala/collection/immutable/Map;Z)V

### ISSUE THREAD

**Issue by detecti1** [allwefantasy/delta-plus#17]
尝试运行readme中的scala代码，除了数据库信息及存储位置外未做修改，spark-submit 成功启动任务，但是在源库发生数据变更时任务会报错退出，报错如标题

引用的版本是 tech.mlsql:mysql-binlog_2.11:1.0.4 、 tech.mlsql:delta-plus_2.11:0.2.0
spark版本是 2.4.3

详细报错内容如下
```
java.lang.NoSuchMethodError: org.apache.spark.sql.delta.schema.ImplicitMetadataOperation$class.updateMetadata(Lorg/apache/spark/sql/delta/schema/ImplicitMetadataOperation;Lorg/apache/spark/sql/delta/OptimisticTransaction;Lorg/apache/spark/sql/Dataset;Lscala/collection/Seq;Lscala/collection/immutable/Map;Z)V
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta.updateMetadata(UpsertTableInDelta.scala:17)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta$$anonfun$_run$4.apply(UpsertTableInDelta.scala:58)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta$$anonfun$_run$4.apply(UpsertTableInDelta.scala:55)
	at org.apache.spark.sql.delta.DeltaLog.withNewTransaction(DeltaLog.scala:396)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta._run(UpsertTableInDelta.scala:55)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta$$anonfun$run$1.apply$mcV$sp(UpsertTableInDelta.scala:31)
	at tech.mlsql.common.DeltaJob$.runWithTry(DeltaJob.scala:17)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta.run(UpsertTableInDelta.scala:30)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$$anonfun$saveToSink$1$1.apply(BinlogSyncToDelta.scala:121)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$$anonfun$saveToSink$1$1.apply(BinlogSyncToDelta.scala:82)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$.saveToSink$1(BinlogSyncToDelta.scala:82)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$.run(BinlogSyncToDelta.scala:132)
	at org.apache.spark.sql.delta.sources.MLSQLDeltaSink.addBatch(MLSQLDeltaSink.scala:31)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$17.apply(MicroBatchExecution.scala:543)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:79)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:144)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:74)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:541)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:62)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:540)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:200)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:168)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:168)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:62)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:168)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:162)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:289)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:200)
20/07/08 18:30:56 INFO [stream execution thread for [id = 16e086fd-21da-4bcc-957d-74a4a919e3d6, runId = 9c977344-6b4c-430d-bc54-90ae9fbb9ad9]] DAGScheduler: Asked to cancel job group 88e44fc0-891d-4e2e-b950-db0be8c39139
20/07/08 18:30:56 INFO [block-manager-slave-async-thread-pool-103] BlockManager: Removing RDD 141
20/07/08 18:30:56 INFO [dispatcher-event-loop-2] BlockManagerInfo: Removed broadcast_26_piece0 on 172.18.80.146:34288 in memory (size: 6.8 KB, free: 366.2 MB)
20/07/08 18:30:56 INFO [dag-scheduler-event-loop] YarnScheduler: Cancelling stage 14
20/07/08 18:30:56 INFO [dag-scheduler-event-loop] YarnScheduler: Killing all running tasks in stage 14: Stage cancelled
20/07/08 18:30:56 INFO [dag-scheduler-event-loop] YarnScheduler: Stage 14 was cancelled
20/07/08 18:30:56 INFO [dag-scheduler-event-loop] DAGScheduler: ResultStage 14 (start at DeltaSync.scala:51) failed in 76.620 s due to Job 5 cancelled part of cancelled job group 88e44fc0-891d-4e2e-b950-db0be8c39139
20/07/08 18:30:56 INFO [launch-binlog-socket-server-in-spark-job] DAGScheduler: Job 5 failed: start at DeltaSync.scala:51, took 76.627967 s
20/07/08 18:30:56 ERROR [stream execution thread for [id = 16e086fd-21da-4bcc-957d-74a4a919e3d6, runId = 9c977344-6b4c-430d-bc54-90ae9fbb9ad9]] SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[stream execution thread for [id = 16e086fd-21da-4bcc-957d-74a4a919e3d6, runId = 9c977344-6b4c-430d-bc54-90ae9fbb9ad9],5,main]
java.lang.NoSuchMethodError: org.apache.spark.sql.delta.schema.ImplicitMetadataOperation$class.updateMetadata(Lorg/apache/spark/sql/delta/schema/ImplicitMetadataOperation;Lorg/apache/spark/sql/delta/OptimisticTransaction;Lorg/apache/spark/sql/Dataset;Lscala/collection/Seq;Lscala/collection/immutable/Map;Z)V
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta.updateMetadata(UpsertTableInDelta.scala:17)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta$$anonfun$_run$4.apply(UpsertTableInDelta.scala:58)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta$$anonfun$_run$4.apply(UpsertTableInDelta.scala:55)
	at org.apache.spark.sql.delta.DeltaLog.withNewTransaction(DeltaLog.scala:396)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta._run(UpsertTableInDelta.scala:55)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta$$anonfun$run$1.apply$mcV$sp(UpsertTableInDelta.scala:31)
	at tech.mlsql.common.DeltaJob$.runWithTry(DeltaJob.scala:17)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta.run(UpsertTableInDelta.scala:30)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$$anonfun$saveToSink$1$1.apply(BinlogSyncToDelta.scala:121)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$$anonfun$saveToSink$1$1.apply(BinlogSyncToDelta.scala:82)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$.saveToSink$1(BinlogSyncToDelta.scala:82)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$.run(BinlogSyncToDelta.scala:132)
	at org.apache.spark.sql.delta.sources.MLSQLDeltaSink.addBatch(MLSQLDeltaSink.scala:31)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$17.apply(MicroBatchExecution.scala:543)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:79)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:144)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:74)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:541)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:62)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:540)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:200)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:168)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:168)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:62)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:168)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:162)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:289)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:200)
20/07/08 18:30:56 ERROR [main] SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[main,5,main]
org.apache.spark.sql.streaming.StreamingQueryException: org.apache.spark.sql.delta.schema.ImplicitMetadataOperation$class.updateMetadata(Lorg/apache/spark/sql/delta/schema/ImplicitMetadataOperation;Lorg/apache/spark/sql/delta/OptimisticTransaction;Lorg/apache/spark/sql/Dataset;Lscala/collection/Seq;Lscala/collection/immutable/Map;Z)V
=== Streaming Query ===
Identifier: [id = 16e086fd-21da-4bcc-957d-74a4a919e3d6, runId = 9c977344-6b4c-430d-bc54-90ae9fbb9ad9]
Current Committed Offsets: {MLSQLBinLogSource(ExecutorBinlogServer(emr-worker-2.cluster-173951,35513),org.apache.spark.sql.SparkSession@2ca67e93,hdfs://emr-header-1.cluster-173951:9000/delta/checkpoints/config/sources/0,Some(40000000243090),Map(binglognameprefix -> mysql-bin, tablenamepattern -> config, databasenamepattern -> lilotest, binlogindex -> 4, username -> root, host -> 172.18.80.1, port -> 3306, binlogserverid -> 88e44fc0-891d-4e2e-b950-db0be8c39139, binlogfileoffset -> 4, password -> password)): 40000000340558}
Current Available Offsets: {MLSQLBinLogSource(ExecutorBinlogServer(emr-worker-2.cluster-173951,35513),org.apache.spark.sql.SparkSession@2ca67e93,hdfs://emr-header-1.cluster-173951:9000/delta/checkpoints/config/sources/0,Some(40000000243090),Map(binglognameprefix -> mysql-bin, tablenamepattern -> config, databasenamepattern -> lilotest, binlogindex -> 4, username -> root, host -> 172.18.80.1, port -> 3306, binlogserverid -> 88e44fc0-891d-4e2e-b950-db0be8c39139, binlogfileoffset -> 4, password -> password)): 40000000340761}

Current State: ACTIVE
Thread State: RUNNABLE

Logical Plan:
MLSQLBinLogSource(ExecutorBinlogServer(emr-worker-2.cluster-173951,35513),org.apache.spark.sql.SparkSession@2ca67e93,hdfs://emr-header-1.cluster-173951:9000/delta/checkpoints/config/sources/0,Some(40000000243090),Map(binglognameprefix -> mysql-bin, tablenamepattern -> config, databasenamepattern -> lilotest, binlogindex -> 4, username -> root, host -> 172.18.80.1, port -> 3306, binlogserverid -> 88e44fc0-891d-4e2e-b950-db0be8c39139, binlogfileoffset -> 4, password -> password))
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:305)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:200)
Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.delta.schema.ImplicitMetadataOperation$class.updateMetadata(Lorg/apache/spark/sql/delta/schema/ImplicitMetadataOperation;Lorg/apache/spark/sql/delta/OptimisticTransaction;Lorg/apache/spark/sql/Dataset;Lscala/collection/Seq;Lscala/collection/immutable/Map;Z)V
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta.updateMetadata(UpsertTableInDelta.scala:17)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta$$anonfun$_run$4.apply(UpsertTableInDelta.scala:58)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta$$anonfun$_run$4.apply(UpsertTableInDelta.scala:55)
	at org.apache.spark.sql.delta.DeltaLog.withNewTransaction(DeltaLog.scala:396)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta._run(UpsertTableInDelta.scala:55)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta$$anonfun$run$1.apply$mcV$sp(UpsertTableInDelta.scala:31)
	at tech.mlsql.common.DeltaJob$.runWithTry(DeltaJob.scala:17)
	at org.apache.spark.sql.delta.commands.UpsertTableInDelta.run(UpsertTableInDelta.scala:30)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$$anonfun$saveToSink$1$1.apply(BinlogSyncToDelta.scala:121)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$$anonfun$saveToSink$1$1.apply(BinlogSyncToDelta.scala:82)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$.saveToSink$1(BinlogSyncToDelta.scala:82)
	at org.apache.spark.sql.delta.commands.BinlogSyncToDelta$.run(BinlogSyncToDelta.scala:132)
	at org.apache.spark.sql.delta.sources.MLSQLDeltaSink.addBatch(MLSQLDeltaSink.scala:31)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$17.apply(MicroBatchExecution.scala:543)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:79)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:144)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:74)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:541)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:62)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:540)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:200)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:168)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:168)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:62)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:168)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:162)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:289)
	... 1 more
20/07/08 18:30:56 INFO [Spark Context Cleaner] ContextCleaner: Cleaned accumulator 811
20/07/08 18:30:56 ERROR [launch-binlog-socket-server-in-spark-job] SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[launch-binlog-socket-server-in-spark-job,5,main]
org.apache.spark.SparkException: Job 5 cancelled part of cancelled job group 88e44fc0-891d-4e2e-b950-db0be8c39139
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1893)
	at org.apache.spark.scheduler.DAGScheduler.handleJobCancellation(DAGScheduler.scala:1824)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply$mcVI$sp(DAGScheduler.scala:906)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply(DAGScheduler.scala:906)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleJobGroupCancelled$1.apply(DAGScheduler.scala:906)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at org.apache.spark.scheduler.DAGScheduler.handleJobGroupCancelled(DAGScheduler.scala:906)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2083)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2063)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2052)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2078)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2099)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2118)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2143)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
	at org.apache.spark.sql.mlsql.sources.MLSQLBinLogDataSource.org$apache$spark$sql$mlsql$sources$MLSQLBinLogDataSource$$launchBinlogServer$1(MLSQLBinLogDataSource.scala:230)
	at org.apache.spark.sql.mlsql.sources.MLSQLBinLogDataSource$$anon$4.run(MLSQLBinLogDataSource.scala:237)
20/07/08 18:30:56 INFO [Spark Context Cleaner] ContextCleaner: Cleaned accumulator 688
20/07/08 18:30:56 INFO [Spark Context Cleaner] ContextCleaner: Cleaned accumulator 813
20/07/08 18:30:56 INFO [Spark Context Cleaner] ContextCleaner: Cleaned accumulator 641
20/07/08 18:30:56 INFO [Spark Context Cleaner] ContextCleaner: Cleaned accumulator 666
20/07/08 18:30:56 INFO [Spark Context Cleaner] ContextCleaner: Cleaned accumulator 645
20/07/08 18:30:56 INFO [Spark Context Cleaner] ContextCleaner: Cleaned accumulator 603
20/07/08 18:30:56 INFO [pool-1-thread-1] SparkContext: Invoking stop() from shutdown hook
20/07/08 18:30:56 INFO [dispatcher-event-loop-3] BlockManagerInfo: Removed broadcast_23_piece0 on emr-worker-1.cluster-173951:46116 in memory (size: 7.7 KB, free: 366.2 MB)
20/07/08 18:30:56 INFO [dispatcher-event-loop-0] BlockManagerInfo: Removed broadcast_23_piece0 on 172.18.80.146:34288 in memory (size: 7.7 KB, free: 366.2 MB)
20/07/08 18:30:56 WARN [task-result-getter-3] TaskSetManager: Lost task 0.0 in stage 14.0 (TID 25, emr-worker-2.cluster-173951, executor 2): TaskKilled (Stage cancelled)
20/07/08 18:30:56 INFO [task-result-getter-3] YarnScheduler: Removed TaskSet 14.0, whose tasks have all completed, from pool 
20/07/08 18:30:56 INFO [pool-1-thread-1] SparkUI: Stopped Spark web UI at http://172.18.80.146:4040
20/07/08 18:30:56 INFO [Spark Context Cleaner] ContextCleaner: Cleaned accumulator 757
20/07/08 18:30:56 INFO [Spark Context Cleaner] ContextCleaner: Cleaned accumulator 598
20/07/08 18:30:56 INFO [Spark Context Cleaner] ContextCleaner: Cleaned accumulator 799
20/07/08 18:30:56 INFO [Spark Context Cleaner] ContextCleaner: Cleaned accumulator 765
20/07/08 18:30:56 INFO [Spark Context Cleaner] ContextCleaner: Cleaned accumulator 821
20/07/08 18:30:56 INFO [Spark Context Cleaner] ContextCleaner: Cleaned accumulator 625
20/07/08 18:30:56 INFO [Spark Context Cleaner] ContextCleaner: Cleaned accumulator 444
20/07/08 18:30:56 INFO [dispatcher-event-loop-1] BlockManagerInfo: Removed broadcast_24_piece0 on 172.18.80.146:34288 in memory (size: 6.9 KB, free: 366.2 MB)
20/07/08 18:30:56 INFO [dispatcher-event-loop-1] BlockManagerInfo: Removed broadcast_24_piece0 on emr-worker-1.cluster-173951:46116 in memory (size: 6.9 KB, free: 366.2 MB)
20/07/08 18:30:56 INFO [YARN application state monitor] YarnClientSchedulerBackend: Interrupting monitor thread
20/07/08 18:30:56 INFO [pool-1-thread-1] YarnClientSchedulerBackend: Shutting down all executors
20/07/08 18:30:56 INFO [dispatcher-event-loop-3] YarnSchedulerBackend$YarnDriverEndpoint: Asking each executor to shut down
20/07/08 18:30:56 INFO [pool-1-thread-1] SchedulerExtensionServices: Stopping SchedulerExtensionServices
(serviceOption=None,
 services=List(),
 started=false)
20/07/08 18:30:56 INFO [pool-1-thread-1] YarnClientSchedulerBackend: Stopped
20/07/08 18:30:56 INFO [dispatcher-event-loop-0] MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
20/07/08 18:30:57 WARN [rpc-server-3-4] NioEventLoop: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@3e4901a7.
20/07/08 18:30:57 INFO [rpc-server-3-4] NioEventLoop: Migrated 1 channel(s) to the new Selector.
20/07/08 18:30:57 INFO [pool-1-thread-1] MemoryStore: MemoryStore cleared
20/07/08 18:30:57 INFO [pool-1-thread-1] BlockManager: BlockManager stopped
20/07/08 18:30:57 INFO [pool-1-thread-1] BlockManagerMaster: BlockManagerMaster stopped
20/07/08 18:30:57 INFO [dispatcher-event-loop-3] OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
20/07/08 18:30:57 INFO [pool-1-thread-1] SparkContext: Successfully stopped SparkContext
20/07/08 18:30:57 INFO [pool-1-thread-1] ShutdownHookManager: Shutdown hook called
20/07/08 18:30:57 INFO [pool-1-thread-1] ShutdownHookManager: Deleting directory /mnt/disk4/yarn/usercache/hadoop/appcache/application_1590480096999_0260/spark-81bfe047-5e8d-4adc-9f0d-b0875bb96379
20/07/08 18:30:57 INFO [pool-1-thread-1] ShutdownHookManager: Deleting directory /mnt/disk1/yarn/usercache/hadoop/appcache/application_1590480096999_0260/spark-592fc41f-ace4-447f-a5b9-2400c9cb4a90
20/07/08 18:30:57 INFO [pool-1-thread-1] ShutdownHookManager: Deleting directory /mnt/disk2/yarn/usercache/hadoop/appcache/application_1590480096999_0260/spark-2ff9606e-a870-49f0-9f0a-e26bab205ad4
20/07/08 18:30:57 INFO [pool-1-thread-1] ShutdownHookManager: Deleting directory /tmp/spark-6c00a8b1-8dac-466e-9256-5a8ed41730be
20/07/08 18:30:57 INFO [pool-1-thread-1] ShutdownHookManager: Deleting directory /mnt/disk3/yarn/usercache/hadoop/appcache/application_1590480096999_0260/spark-4014cb74-369a-4a52-a6ef-64a9afb0c53d

=================JOB OUTPUT END=================
```

**Comment by detecti1** [comment]
版本冲突问题，由于平台提供了不同版本的jar包导致，清理后解决。
